#!/bin/bash

if [ -z "$1" ]; then
 echo "Usage: run <command>"
 exit 1
fi

case "$1" in
 android)
  echo "building android...."
  if [ ! -d "./android" ]; then
   echo "please run `./build android` first"
   exit 1
  fi
  cd android
  ./gradlew assembleDebug
  ;;

 web)
  npm run serve
  ;;
 *)
  echo "Unknown Command: $1"
  echo "Available command: android,  web"
 exit 1
  ;;
esac
