#!/bin/bash

if [ -z "$1" ]; then
 echo "Usage: build <command>"
 exit 1
fi

npm run build

case "$1" in
 android)
  echo "setting android..."
  if [ ! -d "./android/" ]; then
   npx cap add android
  fi
  npx cap sync android
  echo "Setting completed!"
  ;;
 ios)
  echo "setting ios..."
  if [ ! -d "./ios/" ]; then
   npx cap add ios
  fi
  npx cap sync ios
  echo "setting completed!"
  ;;
 *)
  echo "Unknown Command: $1"
  echo "Available command: android, ios"
 exit 1
  ;;
esac
